### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by nagybal** [gyp/ofxstatement-otp#3]
I have tried to install on macOS. What am I missing?

```
iMac:ofxstatement-otp-master bigb$ sudo python setup.py install
Password:
running install
running bdist_egg
running egg_info
creating src/ofxstatement_otp.egg-info
writing requirements to src/ofxstatement_otp.egg-info/requires.txt
writing src/ofxstatement_otp.egg-info/PKG-INFO
writing namespace_packages to src/ofxstatement_otp.egg-info/namespace_packages.txt
writing top-level names to src/ofxstatement_otp.egg-info/top_level.txt
writing dependency_links to src/ofxstatement_otp.egg-info/dependency_links.txt
writing entry points to src/ofxstatement_otp.egg-info/entry_points.txt
writing manifest file 'src/ofxstatement_otp.egg-info/SOURCES.txt'
reading manifest file 'src/ofxstatement_otp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/ofxstatement_otp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.15-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/ofxstatement
copying src/ofxstatement/__init__.py -> build/lib/ofxstatement
creating build/lib/ofxstatement/plugins
copying src/ofxstatement/plugins/otp_credit.py -> build/lib/ofxstatement/plugins
copying src/ofxstatement/plugins/otp.py -> build/lib/ofxstatement/plugins
copying src/ofxstatement/plugins/__init__.py -> build/lib/ofxstatement/plugins
creating build/bdist.macosx-10.15-x86_64
creating build/bdist.macosx-10.15-x86_64/egg
creating build/bdist.macosx-10.15-x86_64/egg/ofxstatement
creating build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins
copying build/lib/ofxstatement/plugins/otp_credit.py -> build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins
copying build/lib/ofxstatement/plugins/otp.py -> build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins
copying build/lib/ofxstatement/plugins/__init__.py -> build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins
copying build/lib/ofxstatement/__init__.py -> build/bdist.macosx-10.15-x86_64/egg/ofxstatement
byte-compiling build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins/otp_credit.py to otp_credit.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins/otp.py to otp.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/ofxstatement/plugins/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.15-x86_64/egg/ofxstatement/__init__.py to __init__.pyc
creating build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/PKG-INFO -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/SOURCES.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/dependency_links.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/entry_points.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/namespace_packages.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/requires.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/top_level.txt -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
copying src/ofxstatement_otp.egg-info/zip-safe -> build/bdist.macosx-10.15-x86_64/egg/EGG-INFO
creating dist
creating 'dist/ofxstatement_otp-0.0.4-py2.7.egg' and adding 'build/bdist.macosx-10.15-x86_64/egg' to it
removing 'build/bdist.macosx-10.15-x86_64/egg' (and everything under it)
Processing ofxstatement_otp-0.0.4-py2.7.egg
Copying ofxstatement_otp-0.0.4-py2.7.egg to /Library/Python/2.7/site-packages
Adding ofxstatement-otp 0.0.4 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/ofxstatement_otp-0.0.4-py2.7.egg
Processing dependencies for ofxstatement-otp==0.0.4
Searching for ofxstatement
Reading https://pypi.org/simple/ofxstatement/
Downloading https://files.pythonhosted.org/packages/33/c2/3f1f0dfa87245bd9880f3aecfc37e0036949d886d712fecdcd5884506280/ofxstatement-0.6.5.tar.gz#sha256=f480615781d7bcf5f15be7ab3bc4ba195bae1b868b5f3bed3ad79a36e7381362
Best match: ofxstatement 0.6.5
Processing ofxstatement-0.6.5.tar.gz
Writing /tmp/easy_install-Prxlxi/ofxstatement-0.6.5/setup.cfg
Running ofxstatement-0.6.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Prxlxi/ofxstatement-0.6.5/egg-dist-tmp-JOvAm9
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    zip_safe=True
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-Prxlxi/ofxstatement-0.6.5/setup.py", line 10, in <module>
    long_description = f.read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 419, in _open
    return _open(path, mode, *args, **kw)
TypeError: 'encoding' is an invalid keyword argument for this function
iMac:ofxstatement-otp-master bigb$ 
```

**Comment by nagybal** [comment]
OK. MacOS does have python 2.7 installed by default. Using v3 did the fix.
`
pip3 install .
`
